# Generated by Django 4.2.5 on 2023-09-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=20)),
                ('zavod', models.CharField(max_length=20)),
                ('yaer', models.IntegerField()),
                ('nomer', models.CharField(max_length=9)),
            ],
        ),
    ]
